theme: jekyll-theme-Mediator
# title: "Dafna Barkan"
# show_downloads: false
# logo:

title: "test web page"

# description: description of your site

#logo: small logo for the site (300x * 300x)

cover: !(https://images.unsplash.com/photo-1507525428034-b723cf961d3e?q=80&w=1000&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8YmVhdXRpZnVsJTIwYmVhY2h8ZW58MHx8MHx8fDA%3D)

name: "Dafna Barkan"

# email: mail address of the site owner

# author: author name

# author_image: small image of author (300x * 300px)

# disqus: add a disqus forum for your post